# Generated by Django 3.2.6 on 2022-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualifiAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qualifi_agency',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'qualifi_brand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('campaign', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('advertiser_name', models.CharField(blank=True, max_length=50, null=True)),
                ('advertiser_id', models.CharField(blank=True, max_length=20, null=True)),
                ('market', models.CharField(blank=True, max_length=50, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('impression_goal', models.BigIntegerField(blank=True, null=True)),
                ('csm', models.CharField(blank=True, max_length=50, null=True)),
                ('sales', models.CharField(blank=True, max_length=50, null=True)),
                ('update_date', models.DateField(blank=True, null=True)),
                ('update_flag', models.BooleanField(blank=True, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'qualifi_campaign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'qualifi_channel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qualifi_market',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiPeople',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'qualifi_people',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualifiPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'qualifi_platform',
                'managed': False,
            },
        ),
    ]
